matrix:
  include:
    - language: node.js
      cache: yarn
      node_js: 14
      services:
        - postgresql
      before_script:
        - cd nodejs
        - ./scripts/travis-ci.before_script
      script:
        - yarn install
        - yarn ci
    - language: node.js
      cache: yarn
      node_js: 15
      services:
        - postgresql
      before_script:
        - cd nodejs
        - ./scripts/travis-ci.before_script
      script:
        - yarn install
        - yarn ci
